export const currencyConstants = {
    FETCH_ALL_DIGITAL_CURRENCIES_REQUEST:"FETCH_ALL_DIGITAL_CURRENCIES_REQUEST",
    FETCH_ALL_DIGITAL_CURRENCIES_FAILURE:"FETCH_ALL_DIGITAL_CURRENCIES_FAILURE",
    FETCH_ALL_DIGITAL_CURRENCIES_SUCCESS:"FETCH_ALL_DIGITAL_CURRENCIES_SUCCESS",

    FETCH_ALL_PHYSICAL_CURRENCIES_REQUEST:"FETCH_ALL_PHYSICAL_CURRENCIES_REQUEST",
    FETCH_ALL_PHYSICAL_CURRENCIES_FAILURE:"FETCH_ALL_PHYSICAL_CURRENCIES_FAILURE",
    FETCH_ALL_PHYSICAL_CURRENCIES_SUCCESS:"FETCH_ALL_PHYSICAL_CURRENCIES_SUCCESS",

    FETCH_DIGITAL_CURRENCY_DATA_REQUEST:"FETCH_DIGITAL_CURRENCY_DATA_REQUEST",
    FETCH_DIGITAL_CURRENCY_DATA_FAILURE:"FETCH_DIGITAL_CURRENCY_DATA_FAILURE",
    FETCH_DIGITAL_CURRENCY_DATA_SUCCESS:"FETCH_DIGITAL_CURRENCY_DATA_SUCCESS",

    SET_SELECTED_CURRENCY:"SET_SELECTED_CURRENCY"

};
