export const currencyConstants = {
    FETCH_ALL_CURRENCIES_REQUEST:"FETCH_ALL_CURRENCIES_REQUEST",
    FETCH_ALL_CURRENCIES_FAILURE:"FETCH_ALL_CURRENCIES_FAILURE",
    FETCH_ALL_CURRENCIES_SUCCESS:"FETCH_ALL_CURRENCIES_SUCCESS",
    SET_SELECTED_CURRENCY:"SET_SELECTED_CURRENCY"

};
