export const equityConstants = {
    FETCH_ALL_REQUEST: "FETCH_ALL_EQUITIES",
    FETCH_ALL_SUCCESS: "FETCH_ALL_SUCCESS",
    FETCH_ALL_FAILURE: "FETCH_ALL_FAILURE",


    EQUITY_DATA_LOADED: "EQUITY_DATA_LOADED",
    EQUITY_DATA_UNLOADED: "EQUITY_DATA_UNLOADED",
    EQUITY_API_TYPES: "EQUITY_API_TYPES",


    SET_SELECTED_EQUITY: "SET_SELECTED_EQUITY",

    EQUITY_DATA_REQUEST:"EQUITY_DATA_REQUEST",
    EQUITY_DATA_FETCH_SUCCESS:"EQUITY_DATA_REQUEST_SUCCESS",
    EQUITY_DATA_FETCH_FAILURE:"EQUITY_DATA_FETCH_FAILURE",


    EQUITY_SUBSCRIBE_REQUEST:"EQUITY_SUBSCRIBE_REQUEST",
    EQUITY_SUBSCRIBE_SUCCESS:"EQUITY_SUBSCRIBE_SUCCESS",
    EQUITY_SUBSCRIBE_FAILURE:"EQUITY_SUBSCRIBE_FAILURE",

    EQUITY_UNSUBSCRIBE_REQUEST:"EQUITY_UNSUBSCRIBE_REQUEST",
    EQUITY_UNSUBSCRIBE_SUCCESS:"EQUITY_UNSUBSCRIBE_SUCCESS",
    EQUITY_UNSUBSCRIBE_FAILURE:"EQUITY_UNSUBSCRIBE_FAILURE"

};