export const equityConstants = {
    FETCH_ALL_REQUEST: "FETCH_ALL_EQUITIES",
    FETCH_ALL_SUCCESS: "FETCH_ALL_SUCCESS",
    FETCH_ALL_FAILURE: "FETCH_ALL_FAILURE",
    EQUITY_DATA_LOADED: "EQUITY_DATA_LOADED",
    EQUITY_DATA_UNLOADED: "EQUITY_DATA_UNLOADED",
    EQUITY_API_TYPES: "EQUITY_API_TYPES",
    SET_SELECTED_EQUITY: "SET_SELECTED_EQUITY"

};